name: Build kernel-cachyos-znver4

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 20 * * *"

env:
  COPR_USERNAME: itotm
  COPR_PROJECT: cachyos-kernel-znver4

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl rpm bc bison dwarves elfutils libdw-dev flex gcc

      - name: Get latest CachyOS/linux tag
        id: tag
        run: |
          TAG=$(curl -s https://api.github.com/repos/CachyOS/linux/tags | jq -r '.[0].name')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          # cachyos-7.0.10-2  →  basekver=7.0, stablekver=10
          BASEKVER=$(echo "$TAG" | sed 's/^cachyos-\([0-9]\+\.[0-9]\+\)\.[0-9]\+-[0-9]\+$/\1/')
          STABLEKVER=$(echo "$TAG" | sed 's/^cachyos-[0-9]\+\.[0-9]\+\.\([0-9]\+\)-[0-9]\+$/\1/')
          echo "basekver=$BASEKVER" >> $GITHUB_OUTPUT
          echo "stablekver=$STABLEKVER" >> $GITHUB_OUTPUT
          echo "Latest tag: $TAG → basekver=$BASEKVER stablekver=$STABLEKVER"

      - name: Build SRPM
        run: |
          rpmbuild -bs \
            --define "_basekver ${{ steps.tag.outputs.basekver }}" \
            --define "_stablekver ${{ steps.tag.outputs.stablekver }}" \
            --define "_tag ${{ steps.tag.outputs.tag }}" \
            sources/kernel-cachyos-bore/kernel-cachyos.spec
